### ISSUE TITLE
invalid GitHubRepo initializer in /app/app.rb:68 on master branch

### ISSUE THREAD

**Issue by Lwangaman** [matthewjackowski/txgh#1]
On the **master branch**, there is an invalid initializer passing two arguments in **/app/app.rb:68**:
```RUBY
github_repo = Strava::L10n::GitHubRepo.new(github_repo_name,github_repo_branch)
```
      
But **/lib/strava/l10n/github_repo.rb** only accepts one argument:
```RUBY
class GitHubRepo

      def initialize(name)
        @name = name
        @config = Strava::Config::KeyManager.github_repo_config(name)
      end
```

Instead in the **heroku branch**, the initializer validly passes only one argument in **/app/app.rb:70**:
```ruby
        github_repo = Strava::L10n::GitHubRepo.new(github_repo_name)
```

**Comment by matthewjackowski** [comment]
Ok this should be fixed now.  I moved the branch setting to a new config entry called 'github_repo_config_branch' so it doesn't need to be passed in to the initializer and was removed as a second argument.

Inside of Heroku it should look like:
![evening-depths-5603_ _settings___heroku](https://cloud.githubusercontent.com/assets/974299/10415323/8a46797e-6fa9-11e5-8c4f-db748a930ee6.jpg)

Fyi, the 'heroku' branch shadows the version I have running as a test instance on Heroku and it had not been updated recently.  Hence the discrepency.
